### ISSUE TITLE
[ERROR] ninj: Error while reading .ninja_deps: failed to fill whole buffer

### ISSUE THREAD

**Issue by sgielen** [m-ou-se/ninj#23]
Sometimes, Ninj gives the following error and exits:

```
[ERROR] ninj: Error while reading .ninja_deps: failed to fill whole buffer
```

I haven't found definitive reproduction steps yet, but my work-around is to just delete the `.ninja_deps` file. I rarely run `ninja` on this project, so I am fairly sure it can happen just from running `cmake -G ninja` and `ninj` in specific ways.

For example, it happens on this .ninja_deps file:

[ninja_deps.gz](https://github.com/m-ou-se/ninj/files/2775809/ninja_deps.gz)

**Comment by sgielen** [comment]
It seems to happen quite often when I interrupt a ninj run with pretty short jobs using ^C. Could be related?

**Comment by m-ou-se** [comment]
Ah yes, the file is simply truncated. Ninja simply 'repairs' such files by cutting it off at the last complete record. We should do that too.

**Comment by m-ou-se** [comment]
Split this into two issues:

- Improve error message. See #22 
- Don't error out on a truncated .ninja_deps file, but instead repair it. See #24
